### ISSUE TITLE
nav

### ISSUE THREAD

**Issue by pastaChaeng** [Brtlyr26/Second#2]
add webpages to be linked.

**Comment by Brtlyr26** [comment]
Alin ba yung need ayusin dito?ho

**Comment by Brtlyr26** [comment]
Dating mag js na ba ito or nilagyan mo?

**Comment by pastaChaeng** [comment]
nilagyan ko bii. ayy pero meron na 'yan nun din pala

**Comment by Brtlyr26** [comment]
ahhhh It works!. thanks
